### ISSUE TITLE
Repeating panic after disk full

### ISSUE THREAD

**Issue by bboreham** [parca-dev/parca#182]
Disk filled up over 10 days (some new variant of #160?); I have retention set to 48h so the WAL-loading could delete from disk anything older than that to make room to carry on.

Logs:

```
level=info ts=2021-04-06T07:35:36.96172537Z caller=repair.go:56 msg="Found healthy block" mint=1616673600299 maxt=1616680800000 ulid=01F1MYCG61DGGS5K79MDK9KVKA
level=info ts=2021-04-06T07:35:36.962234402Z caller=repair.go:56 msg="Found healthy block" mint=1616680800299 maxt=1616688000000 ulid=01F1N587FFB0TDN2TH8WCJXRBH
level=info ts=2021-04-06T07:35:36.962638248Z caller=repair.go:56 msg="Found healthy block" mint=1616688000299 maxt=1616695200000 ulid=01F1NC3YPMEHQ5M9TZB67SFRJT
level=info ts=2021-04-06T07:35:36.963043103Z caller=repair.go:56 msg="Found healthy block" mint=1616695200299 maxt=1616702400000 ulid=01F1NJZNYVBXQQ09KES0V8Z75M
level=info ts=2021-04-06T07:35:36.96356289Z caller=repair.go:56 msg="Found healthy block" mint=1616702400299 maxt=1616709600000 ulid=01F1NSVD73EWPP3TX65NQDV522
level=info ts=2021-04-06T07:35:36.964100637Z caller=repair.go:56 msg="Found healthy block" mint=1616709600299 maxt=1616716800000 ulid=01F1P0Q4FAGA7X3CHAYJTR9EGS
level=info ts=2021-04-06T07:35:36.964636024Z caller=repair.go:56 msg="Found healthy block" mint=1616716800299 maxt=1616724000000 ulid=01F1P7JVQ22J7CNYPRES2RJR6Q
level=info ts=2021-04-06T07:35:36.965083455Z caller=repair.go:56 msg="Found healthy block" mint=1616724000299 maxt=1616731200000 ulid=01F1PEEJZHRTP4A2Y8XJ16K7X8
level=info ts=2021-04-06T07:35:36.965460183Z caller=repair.go:56 msg="Found healthy block" mint=1616731200299 maxt=1616738400000 ulid=01F1PNAA78S6HSXT1P193ME43B
level=info ts=2021-04-06T07:35:36.965930078Z caller=repair.go:56 msg="Found healthy block" mint=1616738400299 maxt=1616745600000 ulid=01F1PW61FBTFMVJNDGNY251DP9
level=info ts=2021-04-06T07:35:36.966404146Z caller=repair.go:56 msg="Found healthy block" mint=1616745600299 maxt=1616752800000 ulid=01F1Q31RQHMJJVR6E4RFVZCXVB
level=info ts=2021-04-06T07:35:36.966444063Z caller=repair.go:56 msg="Found healthy block" mint=1616752800299 maxt=1616760000000 ulid=01F1Q9XFZHEKDR88STFV75ZPJ3
level=info ts=2021-04-06T07:35:36.966476481Z caller=repair.go:56 msg="Found healthy block" mint=1616760000299 maxt=1616767200000 ulid=01F1QGS77SPMQXQFX7V3AZVM0B
level=info ts=2021-04-06T07:35:36.966504145Z caller=repair.go:56 msg="Found healthy block" mint=1616767200299 maxt=1616774400000 ulid=01F1QQMYG9BK8FV0426PP98001
level=info ts=2021-04-06T07:35:36.966529885Z caller=repair.go:56 msg="Found healthy block" mint=1616774400299 maxt=1616781600000 ulid=01F1QYGNQR9PQZ3QC53GAZ5HDV
level=info ts=2021-04-06T07:35:36.9665685Z caller=repair.go:56 msg="Found healthy block" mint=1616781600299 maxt=1616788800000 ulid=01F1R5CD1JQY8NA5K7MCXQZGHZ
level=info ts=2021-04-06T07:35:36.966600231Z caller=repair.go:56 msg="Found healthy block" mint=1616788800299 maxt=1616796000000 ulid=01F1RC847SJFJ07GXPSVSY34YT
level=info ts=2021-04-06T07:35:36.96663212Z caller=repair.go:56 msg="Found healthy block" mint=1616796000299 maxt=1616803200000 ulid=01F1RK3VG0MWSPE5J9X3X9ME10
level=info ts=2021-04-06T07:35:36.966655024Z caller=repair.go:56 msg="Found healthy block" mint=1616803200299 maxt=1616810400000 ulid=01F1RSZJQSKR62J2NZNVQR5QK8
level=info ts=2021-04-06T07:35:36.966681121Z caller=repair.go:56 msg="Found healthy block" mint=1616810400299 maxt=1616817600000 ulid=01F1S0VA12ZFY3256E91RWXYN6
level=info ts=2021-04-06T07:35:36.96670512Z caller=repair.go:56 msg="Found healthy block" mint=1616817600299 maxt=1616824800000 ulid=01F1S7Q182TW507DR5XXWE8F7W
level=info ts=2021-04-06T07:35:36.966735466Z caller=repair.go:56 msg="Found healthy block" mint=1616824800299 maxt=1616832000000 ulid=01F1SEJRFWD0F3KKRS0RE02ZT4
level=info ts=2021-04-06T07:35:36.966762919Z caller=repair.go:56 msg="Found healthy block" mint=1616832000299 maxt=1616839200000 ulid=01F1SNEFQPWA3963ECBW3XMHN7
level=info ts=2021-04-06T07:35:36.966792714Z caller=repair.go:56 msg="Found healthy block" mint=1616839200299 maxt=1616846400000 ulid=01F1SWA718EJ6TSQ2NP9E0P47F
level=info ts=2021-04-06T07:35:36.966820726Z caller=repair.go:56 msg="Found healthy block" mint=1616846400299 maxt=1616853600000 ulid=01F1T35Y7ZGZ5QX4Y8FE6S5J51
level=info ts=2021-04-06T07:35:37.903768269Z caller=head.go:645 msg="Replaying on-disk memory mappable chunks if any"
level=error ts=2021-04-06T07:41:43.422986311Z caller=head.go:650 msg="Loading on-disk chunks failed" err="iterate on on-disk chunks: corruption in head chunk file /conprof/chunks_head/001863: head chunk file doesn't include enough bytes to read the chunk header - required:86466866, available:85798912, file:1863"
level=info ts=2021-04-06T07:41:43.426695199Z caller=head.go:765 msg="Deleting mmapped chunk files"
level=info ts=2021-04-06T07:41:43.450681764Z caller=head.go:772 msg="Deletion of mmap chunk files successful, reattempting m-mapping the on-disk chunks"
level=info ts=2021-04-06T07:47:49.87658567Z caller=head.go:659 msg="On-disk memory mappable chunks replay completed" duration=12m11.970854771s
level=info ts=2021-04-06T07:47:49.891494928Z caller=head.go:665 msg="Replaying WAL, this may take a while"
level=info ts=2021-04-06T07:47:49.919569448Z caller=head.go:691 msg="WAL checkpoint loaded"
level=info ts=2021-04-06T07:47:50.494106937Z caller=head.go:717 msg="WAL segment loaded" segment=1119 maxSegment=1846
level=info ts=2021-04-06T07:47:51.030400371Z caller=head.go:717 msg="WAL segment loaded" segment=1120 maxSegment=1846
level=info ts=2021-04-06T07:47:51.576565009Z caller=head.go:717 msg="WAL segment loaded" segment=1121 maxSegment=1846
[...]
level=info ts=2021-04-06T07:54:36.322256103Z caller=head.go:717 msg="WAL segment loaded" segment=1838 maxSegment=1846
level=info ts=2021-04-06T07:54:36.968940251Z caller=head.go:717 msg="WAL segment loaded" segment=1839 maxSegment=1846
panic: write /conprof/chunks_head/001863: no space left on device

goroutine 12368 [running]:
github.com/conprof/db/tsdb.(*memSeries).mmapCurrentHeadChunk(0xc001056b40, 0xc000282300)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2049 +0x21a
github.com/conprof/db/tsdb.(*memSeries).cutNewHeadChunk(0xc001056b40, 0x178a5c431b8, 0xc000282300, 0xc000d694b8)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2020 +0x39
github.com/conprof/db/tsdb.(*memSeries).append(0xc001056b40, 0x178a5c431b8, 0xc004516000, 0x36326, 0x36326, 0x0, 0xc000282300, 0x1)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2176 +0x493
github.com/conprof/db/tsdb.(*Head).processWALSamples(0xc0004d8000, 0x17873fc0700, 0xc0005353e0, 0xc000535380, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:374 +0x325
github.com/conprof/db/tsdb.(*Head).loadWAL.func5(0xc0004d8000, 0xc000362420, 0xc000362430, 0xc0005353e0, 0xc000535380)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:468 +0x48
created by github.com/conprof/db/tsdb.(*Head).loadWAL
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:467 +0x385
panic: write /conprof/chunks_head/001863: no space left on device

goroutine 12567 [running]:
github.com/conprof/db/tsdb.(*memSeries).mmapCurrentHeadChunk(0xc00101dd40, 0xc000282300)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2049 +0x21a
github.com/conprof/db/tsdb.(*memSeries).cutNewHeadChunk(0xc00101dd40, 0x178a5c43be4, 0xc000282300, 0xc000fec438)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2020 +0x39
github.com/conprof/db/tsdb.(*memSeries).append(0xc00101dd40, 0x178a5c43be4, 0xc0008ec000, 0x1c93, 0x1c93, 0x0, 0xc000282300, 0x26fffa3bf0770001)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2176 +0x493
github.com/conprof/db/tsdb.(*Head).processWALSamples(0xc0004d8000, 0x17873fc0700, 0xc000535920, 0xc0005358c0, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:374 +0x325
github.com/conprof/db/tsdb.(*Head).loadWAL.func5(0xc0004d8000, 0xc000362420, 0xc000362430, 0xc000535920, 0xc0005358c0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:468 +0x48
created by github.com/conprof/db/tsdb.(*Head).loadWAL
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:467 +0x385
panic: write /conprof/chunks_head/001863: no space left on device

goroutine 12561 [running]:
github.com/conprof/db/tsdb.(*memSeries).mmapCurrentHeadChunk(0xc001010900, 0xc000282300)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2049 +0x21a
github.com/conprof/db/tsdb.(*memSeries).cutNewHeadChunk(0xc001010900, 0x178a5c432d1, 0xc000282300, 0xc001428138)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2020 +0x39
github.com/conprof/db/tsdb.(*memSeries).append(0xc001010900, 0x178a5c432d1, 0xc001cfe600, 0x193e, 0x193e, 0x0, 0xc000282300, 0x90fa05a7309d0001)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2176 +0x493
github.com/conprof/db/tsdb.(*Head).processWALSamples(0xc0004d8000, 0x17873fc0700, 0xc0005354a0, 0xc000535440, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:374 +0x325
github.com/conprof/db/tsdb.(*Head).loadWAL.func5(0xc0004d8000, 0xc000362420, 0xc000362430, 0xc0005354a0, 0xc000535440)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:468 +0x48
created by github.com/conprof/db/tsdb.(*Head).loadWAL
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:467 +0x385
panic: write /conprof/chunks_head/001863: no space left on device

goroutine 12364 [running]:
github.com/conprof/db/tsdb.(*memSeries).mmapCurrentHeadChunk(0xc000f666c0, 0xc000282300)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2049 +0x21a
github.com/conprof/db/tsdb.(*memSeries).cutNewHeadChunk(0xc000f666c0, 0x178a5c444cb, 0xc000282300, 0x464780)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2020 +0x39
github.com/conprof/db/tsdb.(*memSeries).append(0xc000f666c0, 0x178a5c444cb, 0xc004670000, 0x4b0fd, 0x4b0fd, 0x0, 0xc000282300, 0xc838bcdab20f0101)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2176 +0x493
github.com/conprof/db/tsdb.(*Head).processWALSamples(0xc0004d8000, 0x17873fc0700, 0xc0005350e0, 0xc000535080, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:374 +0x325
github.com/conprof/db/tsdb.(*Head).loadWAL.func5(0xc0004d8000, 0xc000362420, 0xc000362430, 0xc0005350e0, 0xc000535080)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:468 +0x48
created by github.com/conprof/db/tsdb.(*Head).loadWAL
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:467 +0x385
panic: write /conprof/chunks_head/001863: no space left on device

goroutine 12366 [running]:
github.com/conprof/db/tsdb.(*memSeries).mmapCurrentHeadChunk(0xc00101cfc0, 0xc000282300)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2049 +0x21a
github.com/conprof/db/tsdb.(*memSeries).cutNewHeadChunk(0xc00101cfc0, 0x178a5c437aa, 0xc000282300, 0xc000583ab8)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2020 +0x39
github.com/conprof/db/tsdb.(*memSeries).append(0xc00101cfc0, 0x178a5c437aa, 0xc0017c2000, 0x88ea, 0x88ea, 0x0, 0xc000282300, 0x741a1083a9640001)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2176 +0x493
github.com/conprof/db/tsdb.(*Head).processWALSamples(0xc0004d8000, 0x17873fc0700, 0xc000535260, 0xc000535200, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:374 +0x325
github.com/conprof/db/tsdb.(*Head).loadWAL.func5(0xc0004d8000, 0xc000362420, 0xc000362430, 0xc000535260, 0xc000535200)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:468 +0x48
created by github.com/conprof/db/tsdb.(*Head).loadWAL
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:467 +0x385
panic: write /conprof/chunks_head/001863: no space left on device

goroutine 12562 [running]:
github.com/conprof/db/tsdb.(*memSeries).mmapCurrentHeadChunk(0xc0004efb00, 0xc000282300)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2049 +0x21a
github.com/conprof/db/tsdb.(*memSeries).cutNewHeadChunk(0xc0004efb00, 0x178a5c44064, 0xc000282300, 0xfa7)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2020 +0x39
github.com/conprof/db/tsdb.(*memSeries).append(0xc0004efb00, 0x178a5c44064, 0xc001eca000, 0xdb2f, 0xdb2f, 0x0, 0xc000282300, 0x6713e4df2bb90001)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:2176 +0x493
github.com/conprof/db/tsdb.(*Head).processWALSamples(0xc0004d8000, 0x17873fc0700, 0xc000535560, 0xc000535500, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:374 +0x325
github.com/conprof/db/tsdb.(*Head).loadWAL.func5(0xc0004d8000, 0xc000362420, 0xc000362430, 0xc000535560, 0xc000535500)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:468 +0x48
created by github.com/conprof/db/tsdb.(*Head).loadWAL
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/head.go:467 +0x385
```

**Comment by brancz** [comment]
That's very odd. Thank you for reporting! We'll need to investigate further. As far as I'm aware we are not seeing this in our infrastructure but it's definitely something we should get to the bottom of!

**Comment by brancz** [comment]
We have an entirely new storage engine that we introduced with the Conprof -> Parca rebrand. :)

Closing here.
