### ISSUE TITLE
Storage growing continuously

### ISSUE THREAD

**Issue by bboreham** [parca-dev/parca#189]
Similar to #160 

Running image `quay.io/conprof/conprof:master-2021-03-01-f8fd707`

Logs:

```
level=info ts=2021-03-20T09:05:00.665857055Z caller=repair.go:56 msg="Found healthy block" mint=1616047200820 maxt=1616054400000 ulid=01F1290BKJ5GW1Y6FDDEKRCW7G
level=info ts=2021-03-20T09:05:00.666912404Z caller=repair.go:56 msg="Found healthy block" mint=1616054403036 maxt=1616061600000 ulid=01F12FW7FZ6Z9P9YTYWDV65DR4
level=info ts=2021-03-20T09:05:00.667966793Z caller=repair.go:56 msg="Found healthy block" mint=1616061600819 maxt=1616068800000 ulid=01F12PQYRSDQ4STE4NTC41AKVP
level=info ts=2021-03-20T09:05:00.668941266Z caller=repair.go:56 msg="Found healthy block" mint=1616068807793 maxt=1616076000000 ulid=01F12XKPAMJAZJ412GQBDHGEA0
level=info ts=2021-03-20T09:05:00.669934706Z caller=repair.go:56 msg="Found healthy block" mint=1616076007793 maxt=1616083200000 ulid=01F134FDKH171WY6F66Z9R0BY9
level=info ts=2021-03-20T09:05:00.671813081Z caller=repair.go:56 msg="Found healthy block" mint=1616083204624 maxt=1616090400000 ulid=01F13BB4TJ4KQBV3AWF21A124E
level=info ts=2021-03-20T09:05:00.673113548Z caller=repair.go:56 msg="Found healthy block" mint=1616090401362 maxt=1616097600000 ulid=01F13J6W2H20KB9KH5EZTFP2SE
level=info ts=2021-03-20T09:05:00.675067994Z caller=repair.go:56 msg="Found healthy block" mint=1616097601362 maxt=1616104800000 ulid=01F13S2KAE3EMM0703EY5RHJNS
level=info ts=2021-03-20T09:05:00.679630297Z caller=repair.go:56 msg="Found healthy block" mint=1616104801362 maxt=1616112000000 ulid=01F13ZYAJ9R6V5KH1KGMTPR7CZ
level=info ts=2021-03-20T09:05:00.680666063Z caller=repair.go:56 msg="Found healthy block" mint=1616112001362 maxt=1616119200000 ulid=01F146T1TAKYE9ZTEJ9D7WYJZJ
level=info ts=2021-03-20T09:05:00.682849596Z caller=repair.go:56 msg="Found healthy block" mint=1616119201362 maxt=1616126400000 ulid=01F14DNS3JZRY2GEYA3WVGG69Q
level=info ts=2021-03-20T09:05:00.685806611Z caller=repair.go:56 msg="Found healthy block" mint=1616126401362 maxt=1616133600000 ulid=01F14MHGAHRFFAB2CRV5S9DHET
level=info ts=2021-03-20T09:05:00.687551182Z caller=repair.go:56 msg="Found healthy block" mint=1616133601362 maxt=1616140800000 ulid=01F14VD7K2GQKMYSHHZ0S4F56P
level=info ts=2021-03-20T09:05:00.69035754Z caller=repair.go:56 msg="Found healthy block" mint=1616140801362 maxt=1616148000000 ulid=01F1528YTCYFN4RT4XKNHMC39H
level=info ts=2021-03-20T09:05:00.694562742Z caller=repair.go:56 msg="Found healthy block" mint=1616148001362 maxt=1616155200000 ulid=01F1594P4PBMB02SV530YK1KTG
level=info ts=2021-03-20T09:05:00.696624049Z caller=repair.go:56 msg="Found healthy block" mint=1616155201362 maxt=1616162400000 ulid=01F15G0DA93GPE6KC2Z34CMQ9Q
level=info ts=2021-03-20T09:05:00.701469423Z caller=repair.go:56 msg="Found healthy block" mint=1616162401362 maxt=1616169600000 ulid=01F15PW4JVKFG5AF1P67A187KZ
level=info ts=2021-03-20T09:05:00.702720972Z caller=repair.go:56 msg="Found healthy block" mint=1616169608107 maxt=1616176800000 ulid=01F15XQX0041Z1QZBE3K0A5VCH
level=info ts=2021-03-20T09:05:00.703995811Z caller=repair.go:56 msg="Found healthy block" mint=1616176808107 maxt=1616184000000 ulid=01F164KM822H66PF8D7SEKDGBG
level=info ts=2021-03-20T09:05:00.706975929Z caller=repair.go:56 msg="Found healthy block" mint=1616184008107 maxt=1616191200000 ulid=01F16BFBGQJZJB7C4Q7TQFDQ79
level=info ts=2021-03-20T09:05:00.70946416Z caller=repair.go:56 msg="Found healthy block" mint=1616191208107 maxt=1616198400000 ulid=01F16JB2RKJJ5MVH5EG0MH08C7
level=info ts=2021-03-20T09:05:00.710617958Z caller=repair.go:56 msg="Found healthy block" mint=1616198408107 maxt=1616205600000 ulid=01F16S6T1MED1MH4B1PC04VGK5
level=info ts=2021-03-20T09:05:00.711793428Z caller=repair.go:56 msg="Found healthy block" mint=1616205608113 maxt=1616212800000 ulid=01F1702H8K3HDJCC48W4YCRWF5
level=info ts=2021-03-20T09:05:00.713111543Z caller=repair.go:56 msg="Found healthy block" mint=1616212808107 maxt=1616220000000 ulid=01F176Y8GKTN76CNWXJ9ACBV58
level=info ts=2021-03-20T09:05:00.714153529Z caller=repair.go:56 msg="Found healthy block" mint=1616220008107 maxt=1616227200000 ulid=01F17DSZ1G7SRN96GHNN6HRTGM
level=info ts=2021-03-20T09:05:00.828963882Z caller=head.go:645 msg="Replaying on-disk memory mappable chunks if any"
level=info ts=2021-03-20T09:05:02.143656931Z caller=head.go:659 msg="On-disk memory mappable chunks replay completed" duration=1.314662583s
level=info ts=2021-03-20T09:05:02.143699268Z caller=head.go:665 msg="Replaying WAL, this may take a while"
level=info ts=2021-03-20T09:05:02.146124123Z caller=head.go:691 msg="WAL checkpoint loaded"
level=info ts=2021-03-20T09:05:03.185826736Z caller=head.go:717 msg="WAL segment loaded" segment=778 maxSegment=781
level=info ts=2021-03-20T09:05:03.767997978Z caller=head.go:717 msg="WAL segment loaded" segment=779 maxSegment=781
level=info ts=2021-03-20T09:05:03.854284011Z caller=head.go:717 msg="WAL segment loaded" segment=780 maxSegment=781
level=info ts=2021-03-20T09:05:03.854512037Z caller=head.go:717 msg="WAL segment loaded" segment=781 maxSegment=781
level=info ts=2021-03-20T09:05:03.854540749Z caller=head.go:722 msg="WAL replay completed" checkpoint_replay_duration=2.454605ms wal_replay_duration=1.70837403s total_replay_duration=3.02554674s
level=info ts=2021-03-20T09:05:03.864061994Z caller=http.go:58 service=http/server component=all msg="listening for requests and metrics" address=:8080
level=info ts=2021-03-20T11:00:02.922515502Z caller=compact.go:506 msg="write block" mint=1616227200000 maxt=1616234400000 ulid=01F17MNG9F801WT9RVBY8NVG93 duration=443.409704ms
level=info ts=2021-03-20T11:00:02.971631633Z caller=db.go:1189 msg="Deleting obsolete block" block=01F1290BKJ5GW1Y6FDDEKRCW7G
level=info ts=2021-03-20T11:00:02.972653402Z caller=head.go:824 msg="Head GC completed" duration=985.675µs
...
level=info ts=2021-03-21T17:00:06.801107645Z caller=compact.go:506 msg="write block" mint=1616335202471 maxt=1616342400000 ulid=01F1AVNGFBSHVW0BWTCMC5720X duration=805.206904ms
level=info ts=2021-03-21T17:00:06.812695433Z caller=db.go:1189 msg="Deleting obsolete block" block=01F15G0DA93GPE6KC2Z34CMQ9Q
level=info ts=2021-03-21T17:00:06.813583581Z caller=head.go:824 msg="Head GC completed" duration=858.446µs
level=info ts=2021-03-21T17:00:06.884057337Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=817 to_segment=819 mint=1616342400000
level=info ts=2021-03-21T17:00:07.175007187Z caller=head.go:921 msg="WAL checkpoint complete" first=817 last=819 duration=291.064796ms
level=info ts=2021-03-21T19:00:07.204408793Z caller=compact.go:506 msg="write block" mint=1616342402471 maxt=1616349600000 ulid=01F1B2H7R4NPXGEQTMG3MZ743P duration=1.183604472s
level=info ts=2021-03-21T19:00:07.242677047Z caller=db.go:1189 msg="Deleting obsolete block" block=01F15PW4JVKFG5AF1P67A187KZ
level=info ts=2021-03-21T19:00:07.243604682Z caller=head.go:824 msg="Head GC completed" duration=892.265µs
level=info ts=2021-03-21T19:00:07.315919134Z caller=checkpoint.go:94 msg="Creating checkpoint" from_segment=820 to_segment=822 mint=1616349600000
level=info ts=2021-03-21T19:00:07.628777951Z caller=head.go:921 msg="WAL checkpoint complete" first=820 last=822 duration=312.982664ms
level=info ts=2021-03-21T21:00:07.014364043Z caller=compact.go:506 msg="write block" mint=1616349602471 maxt=1616356800000 ulid=01F1B9CZ0H5BWRB1XK6DX1E4Y1 duration=981.129794ms
2021/03/22 17:24:20 Serving web UI on  http://localhost:0
2021/03/22 17:24:25 Serving web UI on  http://localhost:0
2021/03/22 17:24:32 Serving web UI on  http://localhost:0
```

Goroutine dump: https://share.polarsignals.com/ae95c3f/

This one perhaps?
```
goroutine 179 [semacquire, 32394 minutes]:
sync.runtime_Semacquire(0xc00036d69c)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00036d69c)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
github.com/conprof/db/tsdb.(*Block).Close(0xc00036d680, 0xc005aef608, 0xc005aef2d0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/block.go:326 +0x6f
github.com/conprof/db/tsdb.(*DB).deleteBlocks(0xc0000d16c0, 0xc005aef608, 0xc005aef456, 0x41c3b80)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:1168 +0x7c5
github.com/conprof/db/tsdb.(*DB).reloadBlocks(0xc0000d16c0, 0x0, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:1043 +0x11e5
github.com/conprof/db/tsdb.(*DB).compactHead(0xc0000d16c0, 0xc004506de0, 0x0, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:871 +0xdf
github.com/conprof/db/tsdb.(*DB).Compact(0xc0000d16c0, 0x0, 0x0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:831 +0x245
github.com/conprof/db/tsdb.(*DB).run(0xc0000d16c0)
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:747 +0x27e
created by github.com/conprof/db/tsdb.open
	/go/pkg/mod/github.com/conprof/db@v0.0.0-20201217141952-41a07eb32021/tsdb/db.go:686 +0x791
```

**Comment by metalmatze** [comment]
Thanks for reporting @bboreham! 

I've taken your profile and focused it on compact: https://share.polarsignals.com/5581065/

When blocks are closed they are waiting for readings to stop possibly relying on it's data.
I'm fairly certain that that's the underlying WaitGroup we're seeing:
https://github.com/conprof/db/blob/master/tsdb/block.go#L326

Most likely we're missing a call to Close() somewhere that blocks this WaitGroup...

**Comment by metalmatze** [comment]
Sadly no luck trying to find places where we missed a `Close()` which on the other hand is good as I also compared the code with Prometheus and we didn't change any thing where we would need to close these blocks.
Looking at your original goroutine profile I was trying to find some goroutine that would eventually read the block and thus block the actual block from closing, but I'm unable to identify such a goroutine... 

Just for my personal understanding: Was conprof otherwise entirely unusable during the time the goroutine was blocked?

**Comment by bboreham** [comment]
It was usable, the "Serving web UI" lines continue.

Restarting conprof triggers massive memory use as at https://github.com/conprof/conprof/issues/160#issuecomment-788166118
plus #183 if I let it run long enough.
After that it recovers.

**Comment by brancz** [comment]
We should make sure https://github.com/conprof/conprof/issues/37 gets done, so we can gather some profiles during startup.

**Comment by brancz** [comment]
We have an entirely new storage engine that we introduced with the Conprof -> Parca rebrand. :)
