### ISSUE TITLE
storage: panic when writing bytes to bstream

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#209]
Running Parca with the agent ingesting on my Kubernetes cluster I could see Parca panic:
```
panic: runtime error: index out of range [211] with length 211

goroutine 498606 [running]:
github.com/parca-dev/parca/pkg/storage/chunkenc.(*bstream).writeByte(...)
	github.com/parca-dev/parca/pkg/storage/chunkenc/bstream.go:107
github.com/parca-dev/parca/pkg/storage/chunkenc.(*rleAppender).Append(0xc007809320, 0x2540be400)
	github.com/parca-dev/parca/pkg/storage/chunkenc/rle.go:76 +0x630
github.com/parca-dev/parca/pkg/storage/chunkenc.(*rleAppender).AppendAt(0xc007809320, 0x18e001d, 0x2540be400)
	github.com/parca-dev/parca/pkg/storage/chunkenc/rle.go:103 +0x7f
github.com/parca-dev/parca/pkg/storage.(*MemSeriesAppender).Append(0xc008d63cc0, 0x18f9c70, 0xc00697a360, 0xc00696f920, 0x0, 0x0)
	github.com/parca-dev/parca/pkg/storage/series.go:268 +0xcd6
github.com/parca-dev/parca/pkg/profilestore.(*ProfileStore).WriteRaw(0xc0000ca8c0, 0x18f9c70, 0xc00697a0c0, 0xc003ef36d0, 0x0, 0x0, 0x0)
	github.com/parca-dev/parca/pkg/profilestore/profilestore.go:115 +0x5cb
github.com/parca-dev/parca/gen/proto/go/parca/profilestore/v1alpha1._ProfileStoreService_WriteRaw_Handler.func1(0x18f9c70, 0xc00697a000, 0x14ddba0, 0xc003ef36d0, 0x0, 0x4151, 0x5, 0x161c928)
	github.com/parca-dev/parca/gen/proto/go/parca/profilestore/v1alpha1/profilestore_grpc.pb.go:80 +0x89
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1(0x18f9c70, 0xc00697a000, 0x14ddba0, 0xc003ef36d0, 0xc00d439040, 0xc0055f1cc8, 0x3, 0x3, 0x1902838, 0xc0003687e0)
	github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/server.go:22 +0x239
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x18f9c70, 0xc00697a000, 0x14ddba0, 0xc003ef36d0, 0x39, 0xc003ef3a90, 0x15d83e9, 0x8)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1(0x18f9c70, 0xc00697a000, 0x14ddba0, 0xc003ef36d0, 0xc00d439040, 0xc00d439060, 0x0, 0x0, 0x0, 0x0)
	github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0xb0
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x18f9c70, 0xc00697a000, 0x14ddba0, 0xc003ef36d0, 0x15d83e9, 0x8, 0x0, 0x0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x63
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1(0x18f9c70, 0xc00697a000, 0x14ddba0, 0xc003ef36d0, 0xc00d439040, 0xc00d439080, 0x0, 0x0, 0x0, 0x0)
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.20.0/interceptor.go:338 +0x709
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x18f9c70, 0xc006935ef0, 0x14ddba0, 0xc003ef36d0, 0xc000065000, 0x0, 0xc0002cbb30, 0x40e318)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x18f9c70, 0xc006935ef0, 0x14ddba0, 0xc003ef36d0, 0xc00d439040, 0xc0055f1cc8, 0xc0040f1ba0, 0x4a2a06, 0x150a2e0, 0xc006935ef0)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xd7
github.com/parca-dev/parca/gen/proto/go/parca/profilestore/v1alpha1._ProfileStoreService_WriteRaw_Handler(0x13ed900, 0xc0000ca8c0, 0x18f9c70, 0xc006935ef0, 0xc00696f860, 0xc00001c540, 0x18f9c70, 0xc006935ef0, 0xc009f696c0, 0x18c)
	github.com/parca-dev/parca/gen/proto/go/parca/profilestore/v1alpha1/profilestore_grpc.pb.go:82 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a0000, 0x19082d8, 0xc005d50fc0, 0xc005d0a7e0, 0xc00001c750, 0x21d7860, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.38.0/server.go:1286 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002a0000, 0x19082d8, 0xc005d50fc0, 0xc005d0a7e0, 0x0)
	google.golang.org/grpc@v1.38.0/server.go:1609 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc003e69a14, 0xc0002a0000, 0x19082d8, 0xc005d50fc0, 0xc005d0a7e0)
	google.golang.org/grpc@v1.38.0/server.go:934 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.38.0/server.go:932 +0x1fd
```

**Comment by fpuc** [comment]
Notes from discord, so we have a record:

me:
```
I just took a look at https://github.com/parca-dev/parca/issues/209

panic: runtime error: index out of range [211] with length 211

goroutine 498606 [running]:
github.com/parca-dev/parca/pkg/storage/chunkenc.(*bstream).writeByte(...)
    github.com/parca-dev/parca/pkg/storage/chunkenc/bstream.go:107
github.com/parca-dev/parca/pkg/storage.(*MemSeriesAppender).Append(0xc008d63cc0, 0x18f9c70, 0xc00697a360, 0xc00696f920, 0x0, 0x0)
    github.com/parca-dev/parca/pkg/storage/series.go:268 +0xcd6


The last line of this function causes the panic

func (b *bstream) writeByte(byt byte) {
    if b.count == 0 {
        b.stream = append(b.stream, 0)
        b.count = 8
    }

    i := len(b.stream) - 1

    // fill up b.b with b.count bits from byt
    b.stream[i] |= byt >> (8 - b.count)

    b.stream = append(b.stream, 0)
    i++
    b.stream[i] = byt << b.count
}


As there is i := len(b.stream) -1 and and an append call it looks to me like there must be a data-race.  Without track of concurrent access I looked up the possible uses of writeByte and if this is still possible.

series.go:func (a *MemSeriesAppender) Append uses a mutex.
series_tree.go:func (t *MemSeriesTree) Insert(  doesn't use a mutex and calls Appender() but is 
also called via func (a *MemSeriesAppender) Append so its mutex protected.

From the git logs it looks like the mutex was moved to a "defer approach" 
a.s.mu.Lock()
defer a.s.mu.Unlock()

Here: https://github.com/parca-dev/parca/commit/21557ec

(From a more clustered approach where /parca/pkg/storage/series.go:268 -> 
a.periods.AppendAt(a.s.numSamples%samplesPerChunk, p.Meta.Period)
was not protected by a mutex.)

The commit is from on Oct 4 -> issue was reported on Sep 30. So it may be this problem is 
already fixed 🙂 Did someone see a similar panic and has another stacktrace?
```

@metalmatze:
```
Thank you for reporting this! 💯 
It hasn't been fixed really, but we're moving to a storage now that doesn't have the ProfileSeries anymore and thus the calls from MemSeriesTree will disappear soon. 
I think this should therefore fix that issue, but I would need to double check to be sure.
I want to start on release v0.6.0 in the next hour. 
With that the new storage without profile trees will be the default.
```

**Comment by metalmatze** [comment]
With #505 we'll remove the profile trees and going forward use a more straight forward storage implementation. I _think_ that should mitigate the problem in the way we access the data (there may still be the chance of this happening though, I need to confirm it).
If you could run `v0.6.0` and see if it comes up still and report back, that would be phenomenal! 
I'll definitely keep an eye out for this!

**Comment by metalmatze** [comment]
We've moved to FrostDB since and this is entirely outdated now.
