### ISSUE TITLE
Panic in `main-01353a88`

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#2111]
```
level=info name=parca ts=2022-11-15T10:58:10.714567281Z caller=factory.go:52 msg="loading bucket configuration"
level=info name=parca ts=2022-11-15T10:58:10.728790614Z caller=badger.go:53 msg="Set nextTxnTs to 0"
level=info name=parca ts=2022-11-15T10:58:10.743321089Z caller=server.go:93 msg="starting server" addr=:7070
level=warn name=parca ts=2022-11-15T10:58:40.802824821Z caller=store.go:457 component=debuginfo buildid=38466d6646306f4f41347178697566794b4234762f685850355648414661366b7548727a70617066552f7958695173697042453147356b7279516d5675302f624357544267526374783639586364546f38542d msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:40.908414735Z caller=store.go:457 component=debuginfo buildid=5a787646795557316d49694f45323955505a78652f50635158414c487251635959626a796c716458732f6a6b566c33516e7753565948534870396567474e2f65464a577a52496476677a6e6164544a36654276 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:40.972953717Z caller=store.go:457 component=debuginfo buildid=0bb7f55fde38fb29e86dffd302834cba54723be6 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=error name=parca ts=2022-11-15T10:58:40.97329031Z caller=symbol.go:268 component=symbolizer file=/tmp/0bb7f55fde38fb29e86dffd302834cba54723be6/debuginfo buildid=0bb7f55fde38fb29e86dffd302834cba54723be6 msg="failed to create symtab liner" err="failed to fetch symbols from object file: failed to read symbol sections: no symbol section"
level=error name=parca ts=2022-11-15T10:58:40.97331749Z caller=symbol.go:204 component=symbolizer msg="failed to open object file" file=/tmp/0bb7f55fde38fb29e86dffd302834cba54723be6/debuginfo buildid=0bb7f55fde38fb29e86dffd302834cba54723be6 err="cannot create a liner from given object file"
level=warn name=parca ts=2022-11-15T10:58:40.973473602Z caller=store.go:408 component=debuginfo buildid=80f00bd98ffd2e1e8a1e94603963c9a9ebdc1dc5 msg="failed to fetch object" err="debug info not found"
level=warn name=parca ts=2022-11-15T10:58:42.428738724Z caller=store.go:457 component=debuginfo buildid=6c47664f6a744c63696f4a58344c514e33696e752f367a4d6643654d4b486831437130644475384b6e2f4a7233654f3653796944357453684962595771442f6b6b4e556871412d4a50316f38496f564c475378 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:42.605333091Z caller=store.go:457 component=debuginfo buildid=4646527469644f4e316f387263493643483839612f5f637a42344f51706a7a4a70443179485a3669732f69436a6a5446446577796a74752d55334453414f2f546654744d5358576676526b31463347486f586b msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:42.754596962Z caller=store.go:408 component=debuginfo buildid=fbbb3cfb1351ae4879456a851397ef94be8339a7 msg="failed to fetch object" err="debug info not found"
level=warn name=parca ts=2022-11-15T10:58:42.755735232Z caller=store.go:457 component=debuginfo buildid=682511e3bf35673b msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=error name=parca ts=2022-11-15T10:58:42.756033265Z caller=symbol.go:268 component=symbolizer file=/tmp/682511e3bf35673b/debuginfo buildid=682511e3bf35673b msg="failed to create symtab liner" err="failed to fetch symbols from object file: failed to read symbol sections: no symbol section"
level=error name=parca ts=2022-11-15T10:58:42.756101346Z caller=symbol.go:204 component=symbolizer msg="failed to open object file" file=/tmp/682511e3bf35673b/debuginfo buildid=682511e3bf35673b err="cannot create a liner from given object file"
level=warn name=parca ts=2022-11-15T10:58:42.811113028Z caller=store.go:457 component=debuginfo buildid=6d306b456547445a6c79526b46385947306559612f6e4751425942494167546d2d4c56664a4a7434702f79655661756a77505a31307330423964757842682f5161324e49687531444939414f7953517654724f msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:42.953823699Z caller=store.go:457 component=debuginfo buildid=587747747474626d6d32675732793239503178612f32682d6e472d49515a6f497950314439776765732f6d4f436a5f306c6c35757837445a4e49373264312f4f4e36457464596c695774754730536b664c7845 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:43.072495554Z caller=store.go:457 component=debuginfo buildid=6c4433636b41554d794f50396564706d793452652f4d7a44545164745951783044465f5166534448572f3975702d364d36384858484573587a474c7031772f5369303531716a445050363777514e4b48543948 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:43.15679307Z caller=store.go:457 component=debuginfo buildid=1878e6b475720c7c51969e69ab2d276fae6d1dee msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=error name=parca ts=2022-11-15T10:58:43.157456046Z caller=symbol.go:268 component=symbolizer file=/tmp/1878e6b475720c7c51969e69ab2d276fae6d1dee/debuginfo buildid=1878e6b475720c7c51969e69ab2d276fae6d1dee msg="failed to create symtab liner" err="failed to fetch symbols from object file: failed to read symbol sections: no symbol section"
level=error name=parca ts=2022-11-15T10:58:43.157539027Z caller=symbol.go:204 component=symbolizer msg="failed to open object file" file=/tmp/1878e6b475720c7c51969e69ab2d276fae6d1dee/debuginfo buildid=1878e6b475720c7c51969e69ab2d276fae6d1dee err="cannot create a liner from given object file"
level=warn name=parca ts=2022-11-15T10:58:43.168382588Z caller=store.go:457 component=debuginfo buildid=4a67756f6c5f356975654871746a6231393244552f735a4e4454365a31545271385a56437874384f5a2f69554e2d4a70735175343766646d45487a6946732f517664705069455f4653506e616e33394b614331 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:44.553766472Z caller=store.go:408 component=debuginfo buildid=18b9a9a8c523e5cfe5b5d946d605d09242f09798 msg="failed to fetch object" err="debug info not found"
level=warn name=parca ts=2022-11-15T10:58:44.602040292Z caller=store.go:457 component=debuginfo buildid=6a4769566451743130533257616346596668497a2f56507479544d2d486d753650504c4d53307450612f507355414c725a4d776a6a566f47394d45652d472f3664646354416f6e663645363636337770354643 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:44.661247085Z caller=store.go:457 component=debuginfo buildid=7b4536f41cdaa5888408e82d0836e33dcf436466 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:44.663233833Z caller=store.go:457 component=debuginfo buildid=60a155176bdcba249f1188660488b467dd32b877 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=error name=parca ts=2022-11-15T10:58:44.663494125Z caller=symbol.go:268 component=symbolizer file=/tmp/60a155176bdcba249f1188660488b467dd32b877/debuginfo buildid=60a155176bdcba249f1188660488b467dd32b877 msg="failed to create symtab liner" err="failed to fetch symbols from object file: failed to read symbol sections: no symbol section"
level=error name=parca ts=2022-11-15T10:58:44.663510576Z caller=symbol.go:204 component=symbolizer msg="failed to open object file" file=/tmp/60a155176bdcba249f1188660488b467dd32b877/debuginfo buildid=60a155176bdcba249f1188660488b467dd32b877 err="cannot create a liner from given object file"
level=warn name=parca ts=2022-11-15T10:58:44.698382591Z caller=store.go:457 component=debuginfo buildid=1cd8213e68083b21 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=warn name=parca ts=2022-11-15T10:58:44.744274139Z caller=store.go:457 component=debuginfo buildid=52d683fd53e75da4dcfe607c8080cdf2d8ae1ce5 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=error name=parca ts=2022-11-15T10:58:44.744680783Z caller=symbol.go:268 component=symbolizer file=/tmp/52d683fd53e75da4dcfe607c8080cdf2d8ae1ce5/debuginfo buildid=52d683fd53e75da4dcfe607c8080cdf2d8ae1ce5 msg="failed to create symtab liner" err="failed to fetch symbols from object file: failed to read symbol sections: no symbol section"
level=error name=parca ts=2022-11-15T10:58:44.744722773Z caller=symbol.go:204 component=symbolizer msg="failed to open object file" file=/tmp/52d683fd53e75da4dcfe607c8080cdf2d8ae1ce5/debuginfo buildid=52d683fd53e75da4dcfe607c8080cdf2d8ae1ce5 err="cannot create a liner from given object file"
level=warn name=parca ts=2022-11-15T10:58:45.126269449Z caller=store.go:408 component=debuginfo buildid=413177684345457a576844716748496e5a572d4e2f514d4c324d647879313539394b457532443131642f6f4f33653857525470466b346c7643484a5873512f5f4b6a4c304559323974673136706a5539613750 msg="failed to fetch object" err="debug info not found"
level=warn name=parca ts=2022-11-15T10:58:45.170974776Z caller=store.go:457 component=debuginfo buildid=634a4a31786b524e324b4c476530654239417a2d2f5334785a4b683030377663722d4a5355727745572f696f756830484970694a687379324d4c696335482f52715250786a47395a4e616e73334b52366f6836 msg="failed to fetch debuginfod file" err="failed to fetch from debuginfod: debug info not found"
level=error name=parca ts=2022-11-15T10:58:45.182856966Z caller=symbol.go:268 component=symbolizer file=/tmp/634a4a31786b524e324b4c476530654239417a2d2f5334785a4b683030377663722d4a5355727745572f696f756830484970694a687379324d4c696335482f52715250786a47395a4e616e73334b52366f6836/debuginfo buildid=634a4a31786b524e324b4c476530654239417a2d2f5334785a4b683030377663722d4a5355727745572f696f756830484970694a687379324d4c696335482f52715250786a47395a4e616e73334b52366f6836 msg="failed to create symtab liner" err="failed to fetch symbols from object file: failed to read symbol sections: no symbol section"
level=error name=parca ts=2022-11-15T10:58:45.182923717Z caller=symbol.go:204 component=symbolizer msg="failed to open object file" file=/tmp/634a4a31786b524e324b4c476530654239417a2d2f5334785a4b683030377663722d4a5355727745572f696f756830484970694a687379324d4c696335482f52715250786a47395a4e616e73334b52366f6836/debuginfo buildid=634a4a31786b524e324b4c476530654239417a2d2f5334785a4b683030377663722d4a5355727745572f696f756830484970694a687379324d4c696335482f52715250786a47395a4e616e73334b52366f6836 err="cannot create a liner from given object file"
panic: runtime error: index out of range [0] with length 0

goroutine 27059 [running]:
github.com/polarsignals/frostdb/pqarrow/builder.(*RecordBuilder).Field(...)
	github.com/polarsignals/frostdb@v0.0.0-20221110172813-5c77b18189f1/pqarrow/builder/recordbuilder.go:72
github.com/polarsignals/frostdb/pqarrow.(*ParquetConverter).NumRows(...)
	github.com/polarsignals/frostdb@v0.0.0-20221110172813-5c77b18189f1/pqarrow/arrow.go:335
github.com/polarsignals/frostdb/pqarrow.(*ParquetConverter).writeDistinctAllColumns(0xc00cd953b0?, {0x4cbbf48?, 0xc00ee1ae80?}, {0xc008e67680?, 0x1?, 0x1?}, {0xc040150900?, 0xc00ee1ae80?, 0x7f57f6987cd0?})
	github.com/polarsignals/frostdb@v0.0.0-20221110172813-5c77b18189f1/pqarrow/arrow.go:408 +0x78f
github.com/polarsignals/frostdb/pqarrow.(*ParquetConverter).Convert(0xc00cd953b0, {0x4cbbf48, 0xc00ee1ae80}, {0x7f57f6987cd0, 0xc00ee4c450})
	github.com/polarsignals/frostdb@v0.0.0-20221110172813-5c77b18189f1/pqarrow/arrow.go:278 +0x4b5
github.com/polarsignals/frostdb.(*Table).Iterator.func1()
	github.com/polarsignals/frostdb@v0.0.0-20221110172813-5c77b18189f1/table.go:725 +0x1e8
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by metalmatze** [comment]
I can imagine this being introduced with the changes in https://github.com/polarsignals/frostdb/pull/247/files
`mergeArrowSchemas` in `pqarrow/arrow.go` seems like a good candidate or maybe `ExpandSchema` in `pqarrow/builder/recordbuilder.go`.

**Comment by metalmatze** [comment]
In this case here, we see that the `outputSchema` is nil and use the `schema` instead. With the panic the `schema` is also nil though.
https://github.com/polarsignals/frostdb/blob/5c77b18189f1fab3485161c4c1e8b6fec90695f5/pqarrow/arrow.go#L204-L206
