### ISSUE TITLE
Panic on `main`

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#2499]
Deployed on demo and saw this panic:

```
panic: arrow/array: index out of range

goroutine 32063 [running]:
github.com/apache/arrow/go/v10/arrow/array.(*Binary).Value(...)
        github.com/apache/arrow/go/v10@v10.0.1/arrow/array/binary.go:53
github.com/parca-dev/parca/pkg/parcacol.StringValueFromDictionary(0xc033786050?, 0x0?)
        github.com/parca-dev/parca/pkg/parcacol/querier.go:475 +0x205
github.com/parca-dev/parca/pkg/parcacol.(*Querier).Values.func1({0xc039a2e570?, 0x0?}, {0x524a3c8, 0xc039a2e570})
        github.com/parca-dev/parca/pkg/parcacol/querier.go:145 +0x15d
github.com/polarsignals/frostdb/query/physicalplan.(*OutputPlan).Callback(0xc0336b51a0?, {0x52333c8?, 0xc016f03a00?}, {0x524a3c8?, 0xc039a2e570?})
        github.com/polarsignals/frostdb@v0.0.0-20230127114537-7817186cf2b4/query/physicalplan/physicalplan.go:68 +0x3d
github.com/polarsignals/frostdb/query/physicalplan.(*Distinction).Callback(0xc00bf7b500, {0x52333c8, 0xc016f03a00}, {0x524a3c8, 0xc039a2e4e0})
        github.com/polarsignals/frostdb@v0.0.0-20230127114537-7817186cf2b4/query/physicalplan/distinct.go:152 +0x543
github.com/polarsignals/frostdb/query/physicalplan.(*Synchronizer).Callback(0xc0336b5080?, {0x52333c8?, 0xc016f03a00?}, {0x524a3c8?, 0xc039a2e4e0?})
        github.com/polarsignals/frostdb@v0.0.0-20230127114537-7817186cf2b4/query/physicalplan/synchronize.go:34 +0xf9
github.com/polarsignals/frostdb/query/physicalplan.(*Distinction).Callback(0xc00bf7b4a0, {0x52333c8, 0xc016f03a00}, {0x524a3c8, 0xc039a2e450})
        github.com/polarsignals/frostdb@v0.0.0-20230127114537-7817186cf2b4/query/physicalplan/distinct.go:152 +0x543
github.com/polarsignals/frostdb/query/physicalplan.(*Projection).Callback(0xc02a62d4f0, {0x52333c8, 0xc016f03a00}, {0x524a3c8, 0xc039a2e3f0})
        github.com/polarsignals/frostdb@v0.0.0-20230127114537-7817186cf2b4/query/physicalplan/project.go:252 +0x19b
github.com/polarsignals/frostdb/query/physicalplan.(*noopOperator).Callback(0x3381be0?, {0x52333c8?, 0xc016f03a00?}, {0x524a3c8?, 0xc039a2e3f0?})
        github.com/polarsignals/frostdb@v0.0.0-20230127114537-7817186cf2b4/query/physicalplan/physicalplan.go:212 +0x35
github.com/polarsignals/frostdb.(*Table).Iterator.func1()
        github.com/polarsignals/frostdb@v0.0.0-20230127114537-7817186cf2b4/table.go:760 +0x5de
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by metalmatze** [comment]
This was fixed in #2507
