### ISSUE TITLE
Someting went wrong when running parca server

### ISSUE THREAD

**Issue by yesy6sysu** [parca-dev/parca#3978]
I use Ubuntu 20.04, run parca following the tutorial `https://www.parca.dev/docs/binary` with following steps:

```
curl -sL https://github.com/parca-dev/parca/releases/download/v0.20.0/parca_0.20.0_`uname -s`_`uname -m`.tar.gz | tar xvfz - parca
curl -sL https://raw.githubusercontent.com/parca-dev/parca/v0.20.0/parca.yaml > parca.yaml
./parca --config-path="parca.yaml"
```

Everytime when parca runs for a few minutes, it stops with following error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5c7b7a]

goroutine 160 [running]:
github.com/go-kit/log.(*context).Log(0xc00ce88d20, {0xc012580d80?, 0x6, 0x2?})
        github.com/go-kit/log@v0.2.1/log.go:168 +0x33a
github.com/parca-dev/parca/pkg/debuginfo.(*DebuginfodClientObjectStorageCache).getAndCache(0xc0017711a0, {0x574d6c0, 0xc00ad940c0}, {0xc00b13dc80, 0x28})
        github.com/parca-dev/parca/pkg/debuginfo/debuginfod.go:248 +0x2c2
github.com/parca-dev/parca/pkg/debuginfo.(*DebuginfodClientObjectStorageCache).Get(0xc0017711a0, {0x574d6c0, 0xc00ad940c0}, {0xc00b13dc80, 0x28})
        github.com/parca-dev/parca/pkg/debuginfo/debuginfod.go:231 +0xb2
github.com/parca-dev/parca/pkg/debuginfo.(*DebuginfodExistsClientCache).Get(0x2?, {0x574d6c0?, 0xc00ad940c0?}, {0xc00b13dc80?, 0x0?})
        github.com/parca-dev/parca/pkg/debuginfo/debuginfod.go:382 +0x2b
github.com/parca-dev/parca/pkg/debuginfo.(*DebuginfodTracingClient).Get(0xc0016f26c0, {0x574d6c0?, 0xc0015405a0?}, {0xc00b13dc80, 0x28})
        github.com/parca-dev/parca/pkg/debuginfo/debuginfod.go:430 +0x28d
github.com/parca-dev/parca/pkg/debuginfo.(*ParallelDebuginfodClients).Get(0xc007dd3400?, {0x574d6c0, 0xc0015405a0}, {0xc00b25f020, 0x17}, {0xc00b13dc80, 0x28})
        github.com/parca-dev/parca/pkg/debuginfo/debuginfod.go:146 +0x6d
github.com/parca-dev/parca/pkg/debuginfo.(*Fetcher).fetchFromDebuginfod(0x2f0af60?, {0x574d6c0?, 0xc0015405a0?}, 0xc00a7dec60?)
        github.com/parca-dev/parca/pkg/debuginfo/fetcher.go:69 +0x75
github.com/parca-dev/parca/pkg/debuginfo.(*Fetcher).FetchDebuginfo(0x3752da0?, {0x574d6c0?, 0xc0015405a0?}, 0x28?)
        github.com/parca-dev/parca/pkg/debuginfo/fetcher.go:51 +0x2f
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).symbolizeLocationsForMapping(0xc0016c7e10, {0x574d6c0, 0xc0015405a0}, 0xc014d2c880, {0xc00898c420, 0x1, 0xc014d2c180?})
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:429 +0x53b
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).Symbolize(0xc0016c7e10, {0x574d6c0, 0xc0015405a0}, {0xc001631000, 0x2a4, 0x7?})
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:297 +0x971
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).runSymbolizationCycle(0xc0016c7e10, {0x574d6c0, 0xc0015405a0})
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:221 +0x152
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).Run.func1()
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:190 +0xf1
github.com/parca-dev/parca/pkg/runutil.Repeat(0xc000f0a020?, 0xc0015d63c0, 0xc007dd3dd8)
        github.com/parca-dev/parca/pkg/runutil/runutil.go:38 +0x82
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).Run(0xc0016c7e10, {0x574d6c0, 0xc0015405a0}, 0x37add20?)
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:188 +0x73
github.com/parca-dev/parca/pkg/parca.Run.func5.1({0x574d6c0?, 0xc0015405a0?})
        github.com/parca-dev/parca/pkg/parca/parca.go:508 +0x3d
runtime/pprof.Do({0x574d6f8?, 0xc0017399f0?}, {{0xc000f0a020?, 0x0?, 0x0?}}, 0xc00175bf40)
        runtime/pprof/runtime.go:51 +0x9d
github.com/parca-dev/parca/pkg/parca.Run.func5()
        github.com/parca-dev/parca/pkg/parca/parca.go:507 +0x1ef
github.com/oklog/run.(*Group).Run.func1({0xc0016f2820?, 0xc0016f2840?})
        github.com/oklog/run@v1.1.0/group.go:38 +0x29
created by github.com/oklog/run.(*Group).Run in goroutine 1
        github.com/oklog/run@v1.1.0/group.go:37 +0x67
```

Anyone figure it out?

**Comment by metalmatze** [comment]
I've followed your steps above and can't reproduce on x86 after 10min. 
What's your `uname -a`?

**Comment by yesy6sysu** [comment]
It's strange that this issue occurred when my Linux kernel was version 5.4.0 x86_64. However, after updating the kernel to version 5.15.0-88-generic, I haven't encountered this problem again.

**Comment by dreamerlzl** [comment]
Ok, it seems that this field (the logger) is never inited properly:
https://github.com/parca-dev/parca/blob/main/pkg/debuginfo/debuginfod.go#L195
