### ISSUE TITLE
No symbols in Node.JS application

### ISSUE THREAD

**Issue by orgads** [parca-dev/parca#4205]
**Describe the bug**
I'm running a Node.JS application (in a Docker container), and trying to profile it, but all I get are addresses.

I pass `--perf-basic-prof` and `--interpreted-frames-native-stack` to node.

Parca agent is running on the host.

**To Reproduce**
I don't know how to reproduce with a small app. The example in parca-demos works fine.

**Expected behavior**
Function names should appear.

**Screenshots** or **Profiles** (using https://pprof.me)
![image](https://github.com/parca-dev/parca-agent/assets/1246544/842f09c7-c6ad-4657-ad29-cb731ca0cd12)

**Logs**
Not sure if it's related, but I get this frequently on the server side.
```
recovered stack trace:
 goroutine 191 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
github.com/parca-dev/parca/pkg/symbol/addr2line.(*DwarfLiner).PCToLines.func1()
        github.com/parca-dev/parca/pkg/symbol/addr2line/dwarf.go:107 +0x45
panic({0x3817a20?, 0xc00f8f1650?})
        runtime/panic.go:914 +0x21f
github.com/parca-dev/parca/pkg/symbol/elfutils.getFunctionName(...)
        github.com/parca-dev/parca/pkg/symbol/elfutils/debuginfofile.go:249
github.com/parca-dev/parca/pkg/symbol/elfutils.(*debugInfoFile).SourceLines(0xc01c1d7e60, 0x1c740)
        github.com/parca-dev/parca/pkg/symbol/elfutils/debuginfofile.go:121 +0x799
github.com/parca-dev/parca/pkg/symbol/addr2line.(*DwarfLiner).PCToLines(0x3752680?, 0xc001a425d0?)
        github.com/parca-dev/parca/pkg/symbol/addr2line/dwarf.go:112 +0x6c
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).pcToLines(0xc001775930, {0x574dfd0, 0xc01c1c4740}, {0xc039f17d70, 0x28}, 0x0?)
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:574 +0x53
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).symbolizeLocationsForMapping(0xc001775930, {0x574d6c0, 0xc000dd93e0}, 0xc01088fe80, {0xc010894d20, 0x4, 0xc01088f080?})
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:517 +0x1afb
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).Symbolize(0xc001775930, {0x574d6c0, 0xc000dd93e0}, {0xc00cc3e000, 0x7312, 0x7?})
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:297 +0x971
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).runSymbolizationCycle(0xc001775930, {0x574d6c0, 0xc000dd93e0})
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:221 +0x152
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).Run.func1()
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:190 +0xf1
github.com/parca-dev/parca/pkg/runutil.Repeat(0xc0012d6020?, 0xc000e08000, 0xc000929dd8)
        github.com/parca-dev/parca/pkg/runutil/runutil.go:38 +0x82
github.com/parca-dev/parca/pkg/symbolizer.(*Symbolizer).Run(0xc001775930, {0x574d6c0, 0xc000dd93e0}, 0x37add20?)
        github.com/parca-dev/parca/pkg/symbolizer/symbolizer.go:188 +0x73
github.com/parca-dev/parca/pkg/parca.Run.func5.1({0x574d6c0?, 0xc000dd93e0?})
        github.com/parca-dev/parca/pkg/parca/parca.go:508 +0x3d
runtime/pprof.Do({0x574d6f8?, 0xc0017739f0?}, {{0xc0012d6020?, 0x0?, 0x0?}}, 0xc000dfff40)
        runtime/pprof/runtime.go:51 +0x9d
github.com/parca-dev/parca/pkg/parca.Run.func5()
        github.com/parca-dev/parca/pkg/parca/parca.go:507 +0x1ef
github.com/oklog/run.(*Group).Run.func1({0xc0017aed00?, 0xc0017aed20?})
        github.com/oklog/run@v1.1.0/group.go:38 +0x29
created by github.com/oklog/run.(*Group).Run in goroutine 1
        github.com/oklog/run@v1.1.0/group.go:37 +0x67
```

**Software (please complete the following information):**
 - Parca Agent Version: `parca-agent, version 0.28.0 (commit: 1a09d0149d53f7e8c60287da7ada11b8ac29bf4d, date: 2023-12-04T14:09:50Z), arch: amd64`
 - Parca Server Version (if applicable): `parca, version 0.20.0 (commit: d2b3947b351823a13da1b29757b4c8901e70e90c)`

**Workload (please complete the following information):**
- Runtime (if applicable): Node.JS

**Environment (please complete the following information):**
- Linux Distribution: Debian Linux 12 (the image is `node:18.18.2-alpine3.18`)
- Linux Version: `6.1.0-13-cloud-amd64`
- Arch: `x86_64`
- Container Runtime (if applicable): Docker 24.0.7

**Comment by javierhonduco** [comment]
Could this be related to https://github.com/parca-dev/parca/issues/2810?

**Comment by orgads** [comment]
Anything I can provide to help debugging this?

**Comment by kakkoyun** [comment]
@orgads Sorry for not getting back to you sooner. Could you check this document for troubleshooting: https://www.polarsignals.com/docs/nodejs#troubleshooting 

We recently discovered some issues regarding some nodejs bugs. 

Let us know if it doesn't help.

**Comment by orgads** [comment]
I'm really not sure what I did different, but it works now. Thanks!

**Comment by brancz** [comment]
For what it's worth we've done _many_ improvements in this area recently, so maybe it was just fixed with that.

**Comment by orgads** [comment]
I use the same versions 😅

**Comment by brancz** [comment]
Ah ok, that's odd then. But glad it works now!

**Comment by orgads** [comment]
Ok, I found out what my problem was. My application is running in Docker, so it writes the perfmap file in /tmp inside the container. I need to map it to the host for perf/parca to work correctly.

**Comment by javierhonduco** [comment]
This should not be a problem, we should be reading the tmp of any process in a different mount namespace... @kakkoyun for your attention

**Comment by orgads** [comment]
Actually I did my current tests with plain perf, so maybe parca did work without it.

Is there a flag for perf that enables reading it from the container?

**Comment by kakkoyun** [comment]
We need to double-check the symbolization https://discord.com/channels/877547706334199818/877547706334199821/1217440802322776094

I'm re-opening the issue to keep track of things.

**Comment by PabloPie** [comment]
Providing more details on my previous comment:

#### Application versions
Nodejs: 20.11.1
Parca agent: v0.28
Parca server: v0.21

We are running nodejs in a container based on `node-20:alpine`, and using [dumb-init](https://github.com/Yelp/dumb-init). I followed [the troubleshooting docs](https://www.polarsignals.com/docs/nodejs#all-i-can-see-is-memory-addresses) and the process is correctly creating the perfmap.

After enabling `--perf-basic-prof-only-functions` and `--interpreted-frames-native-stack` I have JIT symbols but no Node runtime symbols
![image](https://github.com/parca-dev/parca/assets/17577492/5da34411-c0f6-4ec2-ad22-5c06645025c9)

**Comment by Finkes** [comment]
Is there any update on this? I just tried it in a `kubernetes` cluster using the default `node:18` docker image with `--perf-basic-prof` enabled and most symbols seem to be missing still.

**Comment by brancz** [comment]
@Finkes the flag should no longer be necessary at all. Can you be more precise in which symbols are missing? Maybe share a screenshot?

**Comment by brancz** [comment]
For more context. Regarding the last screenshot shared here. All nodejs frames themselves seem symbolized correctly, it’s the node binary symbols themselves that are not, this typically happens because the binary simply doesn’t have any symbols in which case there is nothing Parca can do - it can’t pull them out of thin air.

**Comment by Finkes** [comment]
@brancz thanks for your explanation. I tried the node.js fibonacci sample from https://github.com/parca-dev/parca-demo and you are right it is working without the flag and also the symbol `fib` is showing up as expected. 

So I guess my problem is completely on my end and rather caused by a mixture of multiple reasons:
- minification of my own code (resulting in cryptic symbols) -> disabling minification fixed it 
- minification / missing symbols in 3rd party npm dependencies 
- 3rd party deps with native bindings
- lots of async code (promises) + the async nature of the node.js event loop

I'm just having a hard time understanding the flame chart and figuring out the trace of execution of my own ts/js function calls but I guess that's rather a general node.js problem. 

<img width="1880" height="920" alt="Image" src="https://github.com/user-attachments/assets/ca12ee7d-1970-468b-b4ad-eebd04f83b5b" />

**Comment by brancz** [comment]
Yeah makes sense! One thing that I'd recommend doing is do a right-click and hide any binaries you're not interested in.

Minification in the js world is indeed an issue that needs solving, but a separate issue from unwinding and symbolization in general. We've had other customers request support for source maps, so eventually we'll probably get to supporting those so that minification isn't an issue any more either.

Async stacks are indeed yet another v8-specific issue. We've done an investigation here as well, and it appears possible to resolve the original stack that launched an async task, so this is a similar situation to source maps, solveable problem but we need time and motivation to solve it.

For both of these problems if there is a company that cares enough to pay for the development of these features can step forward and expedite it that way 🙂 .
