### ISSUE TITLE
Parca v0.22 panic in arrow/array

### ISSUE THREAD

**Issue by gites** [parca-dev/parca#5033]
After upgrading Parca to v0.22 (and Parca Agent to v0.32) I'm seeing it constantly crashing with this panic: 

```
{"addr":":7070","caller":"server.go:90","level":"info","msg":"starting server","name":"parca","ts":"2024-08-28T13:22:01.970854348Z"}
panic: arrow/array: index out of range

goroutine 121997 [running]:
github.com/apache/arrow/go/v16/arrow/array.(*Binary).Value(...)
        github.com/apache/arrow/go/v16@v16.1.0/arrow/array/binary.go:56
github.com/parca-dev/parca/pkg/profile.serializedArrowLocationSize(0xc02b1cd7a0?, 0x4c?, 0x0?, 0x0, 0x0, {0xc02d379980?, 0x3?, 0x1?}, {0x0, 0x0, ...}, ...)
        github.com/parca-dev/parca/pkg/profile/encode.go:397 +0xe38
github.com/parca-dev/parca/pkg/profile.EncodeArrowLocation(0x7de3aebae4f3f38e, 0x1, 0x0, 0x0, 0x0, {0xc02d379980, 0x3, 0x3?}, {0x0, 0x0, ...}, ...)
        github.com/parca-dev/parca/pkg/profile/encode.go:296 +0x125
github.com/parca-dev/parca/pkg/normalizer.(*arrowToInternalConverter).AddLocationsRecordV1(0xc02b1cdf28, {0xc00a27d240?, 0x0?}, {0x5b6cf30, 0xc00fae8db0})
        github.com/parca-dev/parca/pkg/normalizer/arrow.go:587 +0x150b
github.com/parca-dev/parca/pkg/normalizer.(*arrowToInternalConverter).AddLocationsRecord(0xc02b1cdf28, {0x5b444a0, 0xc0375a42a0}, {0x5b6cf30, 0xc00fae8db0})
        github.com/parca-dev/parca/pkg/normalizer/arrow.go:130 +0x189
github.com/parca-dev/parca/pkg/profilestore.(*ProfileColumnStore).write(0xc0016d0420, {0x5b444a0, 0xc0375a42a0}, {0x5b5ddf8, 0xc03e5934e0})
        github.com/parca-dev/parca/pkg/profilestore/profilecolumnstore.go:270 +0x9ac
github.com/parca-dev/parca/pkg/profilestore.(*ProfileColumnStore).Write.func1()
        github.com/parca-dev/parca/pkg/profilestore/profilecolumnstore.go:180 +0x30
created by github.com/parca-dev/parca/pkg/profilestore.(*ProfileColumnStore).Write in goroutine 121996
        github.com/parca-dev/parca/pkg/profilestore/profilecolumnstore.go:179 +0x11f
```

Happy to provide more debug info if needed.

**Comment by metalmatze** [comment]
Thanks for reporting. We'll look into that!

**Comment by gites** [comment]
Another panic message:

```
{"caller":"recovery.go:24","db":"parca","err":"interface conversion: builder.ColumnBuilder is *builder.ListBuilder, not *builder.OptBinaryBuilder","level":"error","msg":"recovered from panic","name":"parca","stacktrace":"goroutine 37992066 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/polarsignals/frostdb.(*Table).Iterator.Do.func4.1()\n\tgithub.com/polarsignals/frostdb@v0.0.0-20240725052109-695fa06b0eb1/recovery/recovery.go:24 +0x145\npanic({0x42f9700?, 0xc01678f770?})\n\truntime/panic.go:770 +0x132\ngithub.com/polarsignals/frostdb/pqarrow/writer.NewBinaryValueWriter({0x5b543e0, 0xc011f020c0}, 0xc018102dd0?)\n\tgithub.com/polarsignals/frostdb@v0.0.0-20240725052109-695fa06b0eb1/pqarrow/writer/writer.go:47 +0x7c\ngithub.com/polarsignals/frostdb/pqarrow.(*ParquetConverter).schemaChanged(0xc0221af180, {0xc01678c908, 0x41, 0x0?})\n\tgithub.com/polarsignals/frostdb@v0.0.0-20240725052109-695fa06b0eb1/pqarrow/arrow.go:443 +0x513\ngithub.com/polarsignals/frostdb/pqarrow.(*ParquetConverter).Convert(0xc0221af180, {0x5b44430, 0xc0
20f04230}, {0x7ff8d9fa83d0, 0xc01504b620}, 0x1?)\n\tgithub.com/polarsignals/frostdb@v0.0.0-20240725052109-695fa06b0eb1/pqarrow/arrow.go:308 +0x33e\ngithub.com/polarsignals/frostdb.(*Table).Iterator.func2()\n\tgithub.com/polarsignals/frostdb@v0.0.0-20240725052109-695fa06b0eb1/table.go:844 +0x8a9\ngithub.com/polarsignals/frostdb.(*Table).Iterator.Do.func4()\n\tgithub.com/polarsignals/frostdb@v0.0.0-20240725052109-695fa06b0eb1/recovery/recovery.go:28 +0x82\ngolang.org/x/sync/errgroup.(*Group).Go.func1()\n\tgolang.org/x/sync@v0.8.0/errgroup/errgroup.go:78 +0x56\ncreated by golang.org/x/sync/errgroup.(*Group).Go in goroutine 37992040\n\tgo
lang.org/x/sync@v0.8.0/errgroup/errgroup.go:75 +0x96\n","ts":"2024-09-05T12:21:55.902471104Z"}
{"caller":"server.go:312","grpc.code":"Unknown","grpc.component":"server","grpc.error":"interface conversion: builder.ColumnBuilder is *builder.ListBuilder, not *builder.OptBinaryBuilder","grpc.method":"ProfileType
s","grpc.method_type":"unary","grpc.service":"parca.query.v1alpha1.QueryService","grpc.start_time":"2024-09-05T12:21:55Z","grpc.time_ms":"794.042","level":"error","msg":"finished call","name":"parca","peer.address"
:"[::1]:55402","protocol":"grpc","ts":"2024-09-05T12:21:55.902555445Z"}
```

**Comment by denisgolius** [comment]
> Thanks for reporting. We'll look into that!

Hey! Any updates on this?

**Comment by brancz** [comment]
https://github.com/parca-dev/parca/pull/5251 should fix it

**Comment by gites** [comment]
Let's test it in the wild 😀

**Comment by brancz** [comment]
Let us know how it goes!

**Comment by gites** [comment]
Running stable since the deployment. Thanks for the fix!
```
parca-0                                                    5/5     Running     0               19h
```
