### ISSUE TITLE
Panic on columnstore branch

### ISSUE THREAD

**Issue by thorfour** [parca-dev/parca#616]
Hit a panic when running a query against the columnstore. Opening up a ticket so I don't misplace the stack trace to fix later.

```
panic: runtime error: index out of range [0] with length 0

goroutine 7332 [running]:
github.com/parca-dev/parca/pkg/columnstore.(*SumAggregation).Aggregate(0x1665bbf, {0x48cc840, 0x6718d60}, {0x6718d60, 0xc00a633430, 0xc008d4cd88})
	/Users/thor/go/src/github.com/parca-dev/parca/pkg/columnstore/aggregate.go:226 +0x125
github.com/parca-dev/parca/pkg/columnstore.(*HashAggregate).Aggregate(0xc00aa73080)
	/Users/thor/go/src/github.com/parca-dev/parca/pkg/columnstore/aggregate.go:205 +0x3cd
github.com/parca-dev/parca/pkg/query.(*ColumnQueryAPI).QueryRange(0xc003614b00, {0x41ddb2a, 0x38bf700}, 0xc00bb74af0)
	/Users/thor/go/src/github.com/parca-dev/parca/pkg/query/columnquery.go:192 +0xd06
github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1._QueryService_QueryRange_Handler.func1({0x48f69e8, 0xc00de978f0}, {0x3fcba40, 0xc00bb74af0})
	/Users/thor/go/src/github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1/query_vtproto.pb.go:165 +0x78
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x48f69e8, 0xc00de978f0}, {0x3fcba40, 0xc00bb74af0}, 0x0, 0xc0113d7278)
	/Users/thor/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20201207153454-9f6bf00c00a7/interceptors/server.go:22 +0x21e
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x48f69e8, 0xc00de978f0}, {0x3fcba40, 0xc00bb74af0})
	/Users/thor/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x48f69e8, 0xc00de978f0}, {0x3fcba40, 0xc00bb74af0}, 0x0, 0xc00aa6ce20)
	/Users/thor/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x48f69e8, 0xc00de978f0}, {0x3fcba40, 0xc00bb74af0})
	/Users/thor/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x48f69e8, 0xc00de97800}, {0x3fcba40, 0xc00bb74af0}, 0xc00aa6ce00, 0xc00aa6ce40)
	/Users/thor/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.28.0/interceptor.go:325 +0x61c
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x48f69e8, 0xc00de97800}, {0x3fcba40, 0xc00bb74af0})
	/Users/thor/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x48f69e8, 0xc00de97800}, {0x3fcba40, 0xc00bb74af0}, 0xc0000c6bb8, 0x3b43280)
	/Users/thor/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbf
github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1._QueryService_QueryRange_Handler({0x3fbc320, 0xc003614b00}, {0x48f69e8, 0xc00de97800}, 0xc0115b3e00, 0xc003221560)
	/Users/thor/go/src/github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1/query_vtproto.pb.go:167 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0036b88c0, {0x494eb80, 0xc00a70a1b0}, 0xc00ce7d0e0, 0xc003221800, 0x66ba600, 0x0)
	/Users/thor/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0036b88c0, {0x494eb80, 0xc00a70a1b0}, 0xc00ce7d0e0, 0x0)
	/Users/thor/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/Users/thor/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/Users/thor/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:919 +0x294

```

**Comment by brancz** [comment]
Closed by b83dc643d8738caaedb372daa0371c254d4dd793
