### ISSUE TITLE
Columnstore panic during in-memory compaction

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#878]
I've encountered this panic a few times now.

It occurs during compaction and splitting a granule here: 

https://github.com/polarsignals/arcticdb/blob/d18095becbbbec09f4ed1935c8814631bc583ee7/table.go#L391

```
panic: runtime error: unsafe.Slice: ptr is nil and len is not zero

goroutine 17977 [running]:
github.com/segmentio/parquet-go.Value.ByteArray(...)
        /Users/brancz/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220330180547-542d8f0815f1/value.go:373
github.com/segmentio/parquet-go.(*byteArrayDictionary).Insert(0x14000019cc0, {0x1403ee9a000, 0x1, 0x1402fce4000?}, {0x140181a8828?, 0x1, 0x1402ecf38f0?})
        /Users/brancz/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220330180547-542d8f0815f1/dictionary.go:126 +0x144
github.com/segmentio/parquet-go.(*indexedColumnBuffer).WriteValues(0x106cd0f18?, {0x140181a8828?, 0x1, 0x1402ecf38f0?})
        /Users/brancz/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220330180547-542d8f0815f1/dictionary.go:462 +0x140
github.com/segmentio/parquet-go.(*indexedColumnBuffer).WriteRow(0x102b00b01?, {0x140181a8828?, 0x14000be3cc8?, 0x100e7804c?})
        /Users/brancz/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220330180547-542d8f0815f1/dictionary.go:473 +0x78
github.com/segmentio/parquet-go.(*optionalColumnBuffer).WriteRow(0x1402ecf38f0, {0x140181a8828?, 0x1, 0x9})
        /Users/brancz/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220330180547-542d8f0815f1/column_buffer.go:320 +0xa4
github.com/segmentio/parquet-go.(*writerColumn).WriteRow(0x14018a16c00, {0x140181a8828, 0x1, 0x9})
        /Users/brancz/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220330180547-542d8f0815f1/writer.go:827 +0xf0
github.com/segmentio/parquet-go.(*writer).WriteRow(0x140181a8600, {0x140181a8780, 0xd, 0x10})
        /Users/brancz/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220330180547-542d8f0815f1/writer.go:600 +0xd4
github.com/segmentio/parquet-go.(*Writer).WriteRow(...)
        /Users/brancz/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220330180547-542d8f0815f1/writer.go:146
github.com/polarsignals/arcticdb.(*TableBlock).splitGranule(0x14015b07400, 0x1400ef38550)
        /Users/brancz/src/github.com/polarsignals/arcticdb/table.go:391 +0x290
github.com/polarsignals/arcticdb.(*TableBlock).compact(0x0?, 0x524e1ec3c46fdfbc?)
        /Users/brancz/src/github.com/polarsignals/arcticdb/table.go:674 +0x50
created by github.com/polarsignals/arcticdb.(*TableBlock).Insert
        /Users/brancz/src/github.com/polarsignals/arcticdb/table.go:330 +0x288
```

So I added a `recover` and printed the schema and row:

```
message parca {
        required int64 duration (INT(64,true));
        optional binary labels.__name__ (STRING);
        optional binary labels.instance (STRING);
        optional binary labels.job (STRING);
        required int64 period (INT(64,true));
        required binary period_type (STRING);
        required binary period_unit (STRING);
        optional binary pprof_labels. (STRING);
        optional int64 pprof_num_labels.bytes (INT(64,true));
        required binary sample_type (STRING);
        required binary sample_unit (STRING);
        required binary stacktrace (STRING);
        required int64 timestamp (INT(64,true));
        required int64 value (INT(64,true));
}
C:0 D:0 R:0 V:0
C:1 D:1 R:0 V:memory_total_inuse_objects_count
C:2 D:1 R:0 V:127.0.0.1:7070
C:3 D:1 R:0 V:default
C:4 D:0 R:0 V:524288
C:5 D:0 R:0 V:space
C:6 D:0 R:0 V:bytes
C:7 D:1 R:0 V:10880
C:8 D:0 R:0 V:inuse_objects
C:9 D:0 R:0 V:count
C:10 D:0 R:0 V:yѮeCy!%% +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmyѮeCy!%%    +ENmnC5P+ p.:D
YGOɺտt
C:11 D:0 R:0 V:1649159051264
C:12 D:0 R:0 V:0
panic: runtime error: unsafe.Slice: ptr is nil and len is not zero [recovered]
```

This looks quite suspicious. I think what's happening is that `pprof_labels.` accidentally slipped into the schema while the row skips this column entirely so printing the row ultimately panics when it arrives at what should be the last value but is undefined.

Not exactly sure where the problem lies, it could be incorrect creation of pprof labels (with an empty label name), incorrect merging of dynamic label values, or incorrect building of rows.

**Comment by brancz** [comment]
This is the profile that was attempted to be written at and paniced:

[1649159051318.pb.gz](https://github.com/parca-dev/parca/files/8418975/1649159051318.pb.gz)

**Comment by brancz** [comment]
Analyzing the data a bit

```
gzip --stdout --uncompress 1649159051318.pb.gz | protoc -I/Users/brancz/src/github.com/google/pprof/proto profile.proto --decode perftools.profiles.Profile
```

It looks like this profile should have never had a `pprof_label`, but every sample has a `pprof_num_label` with a value.

**Comment by brancz** [comment]
Fixed by https://github.com/polarsignals/arcticdb/pull/23
